import { Product } from "@/context/BoutiqueCartContext";

export const PRODUITS: Product[] = [
  // ── MÉNAGER ──────────────────────────────────────
  {
    id: 1,
    nom: "Réfrigérateur Samsung 260L No-Frost",
    prix_cdf: 1_120_000,
    prix_usd: 400,
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&q=80",
    categorie: "menager",
    sous_categorie: "refrigerateur",
    marque: "Samsung",
    disponible: true,
    stock: 8,
    description: "Réfrigérateur double porte avec technologie No-Frost, classe A+, idéal pour les familles.",
    specifications: { Capacité: "260 L", Énergie: "A+", Couleur: "Argent", Dimensions: "180 x 60 x 65 cm" },
  },
  {
    id: 2,
    nom: "Cuisinière Gaz 4 Feux + Four Hisense",
    prix_cdf: 560_000,
    prix_usd: 200,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
    categorie: "menager",
    sous_categorie: "cuisiniere",
    marque: "Hisense",
    disponible: true,
    stock: 15,
    description: "Cuisinière à gaz 4 feux avec four intégré, grille inox, allumage automatique.",
    specifications: { Feux: "4", Four: "Oui", Allumage: "Automatique", Matière: "Inox/Émail" },
  },
  {
    id: 3,
    nom: "Machine à laver LG 7kg Front Load",
    prix_cdf: 840_000,
    prix_usd: 300,
    image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&q=80",
    categorie: "menager",
    sous_categorie: "lave-linge",
    marque: "LG",
    disponible: true,
    stock: 5,
    description: "Lave-linge frontal 7kg, moteur Direct Drive, programme vapeur, 14 cycles.",
    specifications: { Capacité: "7 kg", Classe: "A+++", Essorage: "1200 tr/min", Programmes: "14" },
  },
  {
    id: 4,
    nom: "Congélateur Coffre Haier 200L",
    prix_cdf: 504_000,
    prix_usd: 180,
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80",
    categorie: "menager",
    sous_categorie: "congelateur",
    marque: "Haier",
    disponible: true,
    stock: 12,
    description: "Congélateur coffre 200L, réfrigération rapide, serrure de sécurité incluse.",
    specifications: { Capacité: "200 L", Température: "-18°C à -24°C", Serrure: "Oui" },
  },
  {
    id: 5,
    nom: "Fer à Repasser Vapeur Philips 2600W",
    prix_cdf: 112_000,
    prix_usd: 40,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    categorie: "menager",
    sous_categorie: "repassage",
    marque: "Philips",
    disponible: true,
    stock: 30,
    description: "Fer à repasser vapeur 2600W, semelle céramique, jet de vapeur 180g/s.",
    specifications: { Puissance: "2600 W", Semelle: "Céramique", Réservoir: "350 ml" },
  },
  {
    id: 6,
    nom: "Mixeur Blender Moulinex 1200W",
    prix_cdf: 168_000,
    prix_usd: 60,
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&q=80",
    categorie: "menager",
    sous_categorie: "cuisine",
    marque: "Moulinex",
    disponible: true,
    stock: 25,
    description: "Blender puissant 1200W, lames inox, bol 1.75L, 5 vitesses + pulse.",
    specifications: { Puissance: "1200 W", Bol: "1.75 L", Vitesses: "5 + Pulse" },
  },
  {
    id: 7,
    nom: "Batterie de Cuisine 10 pièces Tefal",
    prix_cdf: 280_000,
    prix_usd: 100,
    image: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&q=80",
    categorie: "menager",
    sous_categorie: "cuisine",
    marque: "Tefal",
    disponible: true,
    stock: 20,
    description: "Set complet 10 pièces antiadhésif Titanium, compatible induction.",
    specifications: { Pièces: "10", Revêtement: "Titanium", Induction: "Oui", Matière: "Aluminium" },
  },
  {
    id: 8,
    nom: "Climatiseur Split Midea 1.5 CV",
    prix_cdf: 700_000,
    prix_usd: 250,
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
    categorie: "menager",
    sous_categorie: "climatisation",
    marque: "Midea",
    disponible: true,
    stock: 6,
    description: "Climatiseur réversible 1.5 CV Inverter, économie d'énergie, télécommande.",
    specifications: { Puissance: "1.5 CV", Type: "Inverter", "R-froid": "A++", Bruit: "22 dB" },
  },

  // ── AUTOMOBILE ───────────────────────────────────
  {
    id: 9,
    nom: "Pneu Bridgestone 205/65R15 94H",
    prix_cdf: 196_000,
    prix_usd: 70,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    categorie: "automobile",
    sous_categorie: "pneus",
    marque: "Bridgestone",
    disponible: true,
    stock: 40,
    description: "Pneu toutes saisons Ecopia, faible résistance au roulement, longue durée.",
    specifications: { Dimension: "205/65 R15", Indice: "94H", Type: "Toutes saisons", Label: "B/A/71" },
  },
  {
    id: 10,
    nom: "Batterie Voiture Bosch 60Ah 540A",
    prix_cdf: 252_000,
    prix_usd: 90,
    image: "https://images.unsplash.com/photo-1609796733773-58e17d7a9cef?w=600&q=80",
    categorie: "automobile",
    sous_categorie: "batteries",
    marque: "Bosch",
    disponible: true,
    stock: 20,
    description: "Batterie auto S4 60Ah démarrage haute performance, sans entretien.",
    specifications: { Capacité: "60 Ah", Courant: "540 A", Polarité: "Droite", Garantie: "2 ans" },
  },
  {
    id: 11,
    nom: "Huile Moteur Total Quartz 5W30 5L",
    prix_cdf: 84_000,
    prix_usd: 30,
    image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80",
    categorie: "automobile",
    sous_categorie: "lubrifiants",
    marque: "Total",
    disponible: true,
    stock: 50,
    description: "Huile synthétique 5W30 ACEA C3, protection maximale moteur essence et diesel.",
    specifications: { Viscosité: "5W30", Volume: "5 L", Norme: "ACEA C3", Type: "Synthétique" },
  },
  {
    id: 12,
    nom: "Autoradio Pioneer Bluetooth USB 2DIN",
    prix_cdf: 168_000,
    prix_usd: 60,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    categorie: "automobile",
    sous_categorie: "electronique",
    marque: "Pioneer",
    disponible: true,
    stock: 15,
    description: "Autoradio 2 DIN Bluetooth, USB, AUX, FM, écran LCD, 4x50W.",
    specifications: { Format: "2 DIN", Bluetooth: "Oui", USB: "Oui", Puissance: "4x50 W" },
  },
  {
    id: 13,
    nom: "Caméra de Recul HD Vision Nocturne",
    prix_cdf: 56_000,
    prix_usd: 20,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=80",
    categorie: "automobile",
    sous_categorie: "electronique",
    marque: "Generic",
    disponible: true,
    stock: 35,
    description: "Caméra de recul 170°, vision nocturne, imperméable IP68, lignes directrices.",
    specifications: { Angle: "170°", Vision: "Nocturne", Indice: "IP68", Résolution: "720P" },
  },
  {
    id: 14,
    nom: "Filtre à Air Bosch Toyota Land Cruiser",
    prix_cdf: 42_000,
    prix_usd: 15,
    image: "https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=600&q=80",
    categorie: "automobile",
    sous_categorie: "filtres",
    marque: "Bosch",
    disponible: true,
    stock: 28,
    description: "Filtre à air haute performance pour Land Cruiser 200 séries, compatibilité OEM.",
    specifications: { Compatibilité: "Land Cruiser 200", Matière: "Papier plissé", OEM: "Oui" },
  },
  {
    id: 15,
    nom: "Balais Essuie-Glace Michelin 24\"/16\"",
    prix_cdf: 28_000,
    prix_usd: 10,
    image: "https://images.unsplash.com/photo-1536700503339-1e4b06520771?w=600&q=80",
    categorie: "automobile",
    sous_categorie: "accessoires",
    marque: "Michelin",
    disponible: false,
    stock: 0,
    description: "Paire de balais essuie-glace aerovip 24\"/16\", silicone haute durabilité.",
    specifications: { Dimensions: "24\" / 16\"", Matière: "Silicone", Type: "Aerovip" },
  },
  {
    id: 16,
    nom: "Jeu de Jantes Aluminium 15\" x4",
    prix_cdf: 504_000,
    prix_usd: 180,
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&q=80",
    categorie: "automobile",
    sous_categorie: "jantes",
    marque: "BBS",
    disponible: true,
    stock: 3,
    description: "Set 4 jantes aluminium 15 pouces, design 5 branches, finition anthracite.",
    specifications: { Taille: "15\"", Matière: "Aluminium", Couleur: "Anthracite", PCD: "5x114.3" },
  },
];

export const CATEGORIES_MENAGER = [
  { id: "refrigerateur", label: "Réfrigérateurs", icon: "🧊" },
  { id: "cuisiniere", label: "Cuisinières", icon: "🍳" },
  { id: "lave-linge", label: "Lave-linge", icon: "👕" },
  { id: "congelateur", label: "Congélateurs", icon: "❄️" },
  { id: "climatisation", label: "Climatisation", icon: "💨" },
  { id: "repassage", label: "Repassage", icon: "👔" },
  { id: "cuisine", label: "Cuisine & Ustensiles", icon: "🥘" },
];

export const CATEGORIES_AUTO = [
  { id: "pneus", label: "Pneus", icon: "🔵" },
  { id: "batteries", label: "Batteries", icon: "⚡" },
  { id: "lubrifiants", label: "Huiles & Lubrifiants", icon: "🛢️" },
  { id: "electronique", label: "Électronique", icon: "📻" },
  { id: "filtres", label: "Filtres", icon: "🔧" },
  { id: "jantes", label: "Jantes", icon: "⭕" },
  { id: "accessoires", label: "Accessoires", icon: "🧰" },
];

export function formatCDF(n: number) {
  return new Intl.NumberFormat("fr-CD", { style: "currency", currency: "CDF", maximumFractionDigits: 0 }).format(n);
}

export function formatUSD(n: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
}
